services:
  tibber.cleaningbotwebapi:
    image: tibber.cleaningbotwebapi
    build:
      context: .
      dockerfile: Tibber.CleaningBotWebAPI/Dockerfile
    ports:
      - "5000:5000"

  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pw
      POSTGRES_DB: robot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: